module.exports = {
	CANVAS_ID: 'hardSpheres',
	CANVAS_DIMENSIONS: 750,

	CONTAINER_RADIUS: 350,
	RMS_SPEED: 50,
	NUM_PARTICLES: 450,
	DEFAULT_RADIUS: 1,

	OUTPUT_FILE_DIRECTORY: './data/',

	MAX_COLLISIONS: 4500
};
